#!/bin/bash
# HarbourOS — Flux Node Installer
# Runs as root. Called by the Admin UI via /api/flux/install.
# Output is streamed to /var/log/harbouros-flux-install.log

set -euo pipefail
LOG="/var/log/harbouros-flux-install.log"
CONFIG="/etc/harbouros/flux.json"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG"; }
fail() { log "ERROR: $*"; exit 1; }

log "=== HarbourOS Flux Node Installer ==="

# ---------------------------------------------------------------
# 1. Pre-flight checks
# ---------------------------------------------------------------
log "[1/5] Running pre-flight checks..."

# Architecture
ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m)
if [[ "$ARCH" != "arm64" && "$ARCH" != "aarch64" ]]; then
    log "WARNING: Architecture is $ARCH (expected arm64). Proceeding anyway."
fi

# RAM check (minimum 7.5 GB)
RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
RAM_GB=$(awk "BEGIN {printf \"%.1f\", $RAM_KB / 1048576}")
if (( RAM_KB < 7340032 )); then
    fail "Insufficient RAM: ${RAM_GB} GB (minimum 7.5 GB required for Cumulus tier)"
fi
log "[OK] RAM: ${RAM_GB} GB"

# Disk write speed check (minimum 180 MB/s)
# Use a temporary 512 MB test file on /
TESTFILE="/tmp/harbouros-flux-disktest"
log "  Testing disk write speed (this takes ~5 seconds)..."
WRITE_RESULT=$(dd if=/dev/zero of="$TESTFILE" bs=1M count=512 conv=fdatasync 2>&1 | tail -1 || true)
rm -f "$TESTFILE"
# Extract MB/s from dd output — may be GB/s on NVMe
WRITE_MBPS=$(echo "$WRITE_RESULT" | grep -oP '[\d.]+(?= MB/s)' | head -1 || echo "")
WRITE_GBPS=$(echo "$WRITE_RESULT" | grep -oP '[\d.]+(?= GB/s)' | head -1 || echo "")
if [ -n "$WRITE_GBPS" ]; then
    log "[OK] Disk write speed: ${WRITE_GBPS} GB/s (well above 180 MB/s minimum)"
elif [ -z "$WRITE_MBPS" ] || awk "BEGIN {exit !($WRITE_MBPS < 50)}"; then
    log "WARNING: Disk write speed ${WRITE_MBPS} MB/s may be below 180 MB/s minimum."
    log "  For Cumulus tier, an external USB 3.0 SSD is required."
    log "  Continuing install — you can re-test after attaching an SSD."
else
    log "[OK] Disk write speed: ${WRITE_MBPS} MB/s"
fi

# ---------------------------------------------------------------
# 2. Install Docker (if missing)
# ---------------------------------------------------------------
log "[2/5] Checking Docker..."
if ! command -v docker &>/dev/null; then
    log "  Docker not found. Installing Docker..."
    curl -fsSL https://get.docker.com | sh >> "$LOG" 2>&1
    usermod -aG docker root 2>/dev/null || true
    systemctl enable docker.service >> "$LOG" 2>&1
    systemctl start docker.service >> "$LOG" 2>&1
    log "[OK] Docker installed."
else
    log "[OK] Docker already installed: $(docker --version 2>/dev/null | head -1)"
fi

# Ensure Docker is running
if ! systemctl is-active --quiet docker; then
    systemctl start docker >> "$LOG" 2>&1
fi

# ---------------------------------------------------------------
# 3. Install FluxNode via official multitool
# ---------------------------------------------------------------
log "[3/5] Installing FluxNode software..."
log "  Downloading FluxNode multitool..."

# Run in non-interactive mode by passing option "1" (Install FluxNode) then "1" (Cumulus)
# The multitool supports FLUX_INSTALL_MODE env var for scripted installs
export FLUX_NONINTERACTIVE=1
bash <(curl -fsSL https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh) \
    >> "$LOG" 2>&1 || {
    log "WARNING: Multitool exited with non-zero status. Checking if zelcash is available..."
}

if ! command -v zelcash &>/dev/null && ! command -v fluxd &>/dev/null; then
    fail "FluxNode installation failed — zelcash/fluxd not found after install."
fi
log "[OK] FluxNode software installed."

# ---------------------------------------------------------------
# 4. Configure fluxd with Insight Explorer mode
# ---------------------------------------------------------------
log "[4/5] Configuring fluxd and installing systemd service..."

# Ensure datadir exists
mkdir -p /var/lib/fluxd
chmod 700 /var/lib/fluxd

# Generate flux.conf if it doesn't exist yet.
# The node-specific fields (zelnode=1, zelnodeprivkey, zelnodeoutpoint, externalip)
# are filled in later via the Admin UI Config tab or manually.
FLUX_CONF="/var/lib/fluxd/flux.conf"
if [ ! -f "$FLUX_CONF" ]; then
    log "  Creating /var/lib/fluxd/flux.conf with Insight Explorer mode..."
    cat > "$FLUX_CONF" << 'FLUXCONF'
# HarbourOS Flux Node Configuration
# Generated by harbouros-flux-install.sh
# Edit zelnode fields and restart the service to activate your node.

# --- Node operation mode ---
server=1
daemon=1
listen=1
txindex=1

# Insight Explorer — required for FluxOS processInsight() path.
# This eliminates P2SH transaction crashes in explorerService.js.
# Do NOT disable — insightexplorer=0 will cause FluxOS explorer errors.
insightexplorer=1
experimentalfeatures=1
addressindex=1
timestampindex=1
spentindex=1

# --- Network ports ---
port=16125
rpcport=16124

# --- RPC credentials (change these) ---
rpcuser=CHANGE_ME_RPC_USER
rpcpassword=CHANGE_ME_RPC_PASSWORD
rpcallowip=127.0.0.1

# --- Zelnode (fill in after collateral TX is confirmed) ---
# zelnode=1
# zelnodeprivkey=YOUR_FLUXNODE_PRIVKEY
# zelnodeoutpoint=YOUR_COLLATERAL_TXID
# zelnodeindex=0
# externalip=YOUR_PUBLIC_IP

# --- Performance ---
dbcache=512
FLUXCONF
    chmod 600 "$FLUX_CONF"
    log "[OK] flux.conf created at $FLUX_CONF"
else
    # Ensure insightexplorer flags are present in existing config
    NEEDS_INSIGHT=0
    grep -q '^insightexplorer=1' "$FLUX_CONF" || NEEDS_INSIGHT=1
    if [ "$NEEDS_INSIGHT" -eq 1 ]; then
        log "  Adding insightexplorer flags to existing flux.conf..."
        cat >> "$FLUX_CONF" << 'INSIGHT'

# Insight Explorer — added by HarbourOS installer
insightexplorer=1
experimentalfeatures=1
addressindex=1
timestampindex=1
spentindex=1
INSIGHT
        log "[OK] insightexplorer flags added to $FLUX_CONF"
    else
        log "[OK] $FLUX_CONF already has insightexplorer=1"
    fi
fi

# Also keep /root/.flux/flux.conf in sync — FluxOS reads from $HOME/.flux/flux.conf
# via os.homedir() when running as root, independent of the -conf= flag passed to fluxd.
mkdir -p /root/.flux
if [ ! -f /root/.flux/flux.conf ] || ! diff -q "$FLUX_CONF" /root/.flux/flux.conf >/dev/null 2>&1; then
    cp "$FLUX_CONF" /root/.flux/flux.conf
    chmod 600 /root/.flux/flux.conf
    log "[OK] /root/.flux/flux.conf synced from $FLUX_CONF"
fi

# Install the zelcash.service systemd unit (official service name used by FluxOS/watchdog)
if [ -f /etc/systemd/system/zelcash.service ]; then
    log "  zelcash.service already exists."
else
    HARBOUROS_FLUX_SVC="/usr/local/share/harbouros/harbouros-flux.service"
    if [ -f "$HARBOUROS_FLUX_SVC" ]; then
        cp "$HARBOUROS_FLUX_SVC" /etc/systemd/system/zelcash.service
        systemctl daemon-reload >> "$LOG" 2>&1
        systemctl enable zelcash.service >> "$LOG" 2>&1
        log "[OK] zelcash.service installed and enabled."
    else
        log "  WARNING: harbouros-flux.service not found at $HARBOUROS_FLUX_SVC — install it manually."
    fi
fi

# Fix fluxbenchd RPC credentials to match what FluxOS expects.
# FluxOS benchmarkService.js uses the well-known credentials fluxbenchuser/fluxbenchpassword.
# The multitool may write different values — correct them here.
BENCH_CONF="/var/lib/fluxbench/fluxbench.conf"
if [ -f "$BENCH_CONF" ]; then
    sed -i 's/^rpcuser=.*/rpcuser=fluxbenchuser/' "$BENCH_CONF"
    sed -i 's/^rpcpassword=.*/rpcpassword=fluxbenchpassword/' "$BENCH_CONF"
    log "[OK] fluxbenchd RPC credentials corrected."
fi

# Open UFW ports for Flux network communication
if command -v ufw &>/dev/null; then
    ufw allow 16124:16129/tcp >> "$LOG" 2>&1 || true
    ufw allow 16124:16129/udp >> "$LOG" 2>&1 || true
    ufw allow 16224/tcp >> "$LOG" 2>&1 || true
    ufw allow 16224/udp >> "$LOG" 2>&1 || true
    log "[OK] UFW rules added for Flux ports 16124-16129 and 16224."
fi

# ---------------------------------------------------------------
# 5. Mark as installed in config
# ---------------------------------------------------------------
log "[5/5] Finalising configuration..."
mkdir -p /etc/harbouros
if [ -f "$CONFIG" ]; then
    # Update installed flag
    python3 -c "
import json, sys
with open('$CONFIG') as f:
    cfg = json.load(f)
cfg['installed'] = True
with open('$CONFIG', 'w') as f:
    json.dump(cfg, f, indent=2)
" 2>>"$LOG" || true
else
    echo '{"installed":true,"collateral_txid":"","collateral_index":"0","zelid":"","public_key":"","api_port":16127}' \
        > "$CONFIG"
fi

log "=== Installation complete. ==="
log ""
log "Next steps:"
log "  1. Edit /var/lib/fluxd/flux.conf — uncomment the zelnode= section and fill in:"
log "       zelnodeprivkey=YOUR_FLUXNODE_PRIVKEY"
log "       zelnodeoutpoint=YOUR_COLLATERAL_TXID"
log "       zelnodeindex=YOUR_COLLATERAL_VOUT"
log "       externalip=YOUR_PUBLIC_IP"
log "       zelnode=1"
log "  2. Set a strong rpcuser and rpcpassword in /var/lib/fluxd/flux.conf."
log "  3. Sync /root/.flux/flux.conf: cp /var/lib/fluxd/flux.conf /root/.flux/flux.conf"
log "  4. Forward ports 16124-16129 (TCP+UDP) and 16224 on your router to this Pi's IP."
log "  5. Start the node: systemctl start zelcash.service"
log "  6. Wait for blockchain sync (initial sync: 1-3 hours; first full insightexplorer"
log "     index build takes 4-5 days on Raspberry Pi 5)."
log "  7. Once synced, run startdeterministicfluxnode from the Admin UI or flux-cli."
